train:
  epochs: &epochs 1000
  optimizer:
    type: torch.optim.SGD
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0005
  scheduler:
    type: torch.optim.lr_scheduler.CosineAnnealingLR
    params:
      T_max: *epochs
      eta_min: 0.0001
  amp: true
  rank@k: 5
  
logdir: "runs"

data:
  type: dataloader.MyHeteroData
  ratings_path: dataset/ml-latest-small/ratings.csv
  movies_path: dataset/ml-latest-small/movies.csv
  links_path: dataset/ml-latest-small/links.csv
  productions_path: dataset/ml-latest-small/links_production.csv
  # ratings_path: dataset/ml-32m/ratings.csv
  # movies_path: dataset/ml-32m/movies.csv
  # links_path: dataset/ml-32m/links.csv
  # productions_path: dataset/ml-32m/links_production.csv
  pos_threshold: 3.5
  val_ratio: 0.2
  test_ratio: 0.1
  batch_size: 1024
  num_neighbors: [20]
  rating_range: &rating_range [0.5, 5.0]
  weight_user_movie:
    type: sigmoid
    k: 3 # elasticity
    c: 3.5 # center
  

model:
  num_layers: 2
  type: "HeteroLightGCN"
  threshold: 0.5
  num_dim: 128
  rating_range: *rating_range
  exclude_node: ['genre', 'director', 'writer', 'star']  
  # exclude_node:
  # - All: [] 
  # - Baseline: ['genre', 'director', 'writer', 'star'] 
  # - Selected `genre` and `star`: ['director', 'writer']