model:
  name: "resnet18"
  num_classes: 10

training:
  epochs: 20
  optimizer:
    type: torch.optim.SGD
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    type: torch.optim.lr_scheduler.CosineAnnealingLR
    params:
      T_max: ${training.epochs}
      eta_min: 0.0001
  amp: true

data:
  type: dataloader.MyHeteroData
  ratings_path: dataset/ml-latest-small/ratings.csv
  movies_path: dataset/ml-latest-small/movies.csv
  links_path: dataset/ml-latest-small/links.csv
  val_ratio: 0.2
  test_ratio: 0.1
  batch_size: 32
  num_neighbors: [200, 100]
  

model:
  name: "HeteroLightGCN"
  num_dim: 128
  